CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  roles JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS user_supports (
  veteran_id UUID NOT NULL,
  support_id UUID NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY (veteran_id, support_id),
  FOREIGN KEY (veteran_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (support_id) REFERENCES users(id) ON DELETE CASCADE
);
