### =====================================================
### Variables
### =====================================================
@baseUrl = http://localhost:8080
@keycloakUrl = http://localhost:8180
@realm = endurance
@clientId = backend
@clientSecret = Hvkh9JcoLjjNFT8FIgd3qPpJZWT3E7v9
@username = Kaj
@password = password

### =====================================================
### Get access token from Keycloak
### =====================================================
POST {{keycloakUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id={{clientId}}&
client_secret={{clientSecret}}&
username={{username}}&
password={{password}}&
scope=openid

> {%
  client.global.set("token", response.body.access_token);
%}

### =====================================================
### Sync current user (GetOrCreate)
### (Uses data from Keycloak token)
### =====================================================
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### =====================================================
### Get user by ID
### (replace with your own UUID from Keycloak)
### =====================================================
GET {{baseUrl}}/users/2e808133-794d-4ba3-8da0-e562131692fb
Authorization: Bearer {{token}}

### =====================================================
### Add SUPPORT member to VETERAN
### (The authenticated user will be added as support member)
### (replace veteranId with actual UUID)
### =====================================================
POST {{baseUrl}}/users/2e808133-794d-4ba3-8da0-e562131692fb/support
Authorization: Bearer {{token}}

### =====================================================
### List SUPPORT members of current VETERAN
### (Uses data from Keycloak token)
### =====================================================
GET {{baseUrl}}/users/support
Authorization: Bearer {{token}}
